version: '3'

services:
  db:
    image: postgres:alpine
    ports:
     - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - myapi-network
  back:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/back
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - myapi-network
  front:
    build: ./frontend/
    command: npm run dev -- --host
    volumes:
      - ./frontend/:/front
    env_file:
      - .env
    ports:
      - 5173:5173
    networks:
      - myapi-network

networks:
  myapi-network:
volumes:
  postgres_data:

